export { default as SharedLayout } from "./SharedLayout";
export { default as Navbar } from "./Navbar";
export { default as Footer} from "./Footer";
export { default as NotFound } from "./NotFound";
export { default as ScrollToTop } from "./ScrollToTop";
export { default as Slide } from "./Slide";
export { default as Service } from "./Service";
export { default as Faq } from "./Faq";
export { default as Post } from "./Post";
export { default as Protected } from "./Protected";
export { default as Loader } from "./Loader";
export { default as Loading } from "./Loading";
export { default as Timer } from "./Timer";
export {default as MailAlert } from "./MailAlert";
export { default as Sidebar } from "./Sidebar";
export { default as UserNavbar } from "./UserNavbar";
export { default as Avatars } from "./Avatars";
export { default as Search } from "./Search";
export { default as UserSearch } from "./UserSearch";
export { default as BouncingText } from "./BouncingText";
export { default as BackToTop } from "./BackToTop";
